import Header from "../Header";
import Footer from "../Footer";
import { useEffect, useState } from "react";

interface CartIdProp {
    cartID: number;
}

interface Cart {
    _id: number; // Cart ID (generated by a counter)
    items: Array<ItemInCart>; // FIX 5: Use a specific interface for items in the cart
}

interface ItemInCart {
    itemId: number; // The _id of the item being referenced
    count: number; // The quantity of this item in the cart
    info: string;
}

const CartItems: React.FC<CartIdProp> = ({ cartID }) => {
    // 1. Initialize state for data and loading/error status
    const [products, setProducts] = useState<Cart>();
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    // 2. Data Fetching Effect (Remains the same)
    useEffect(() => {
        // ... (fetchProducts function remains the same as in your original code)
        const fetchProducts = async () => {
            try {
                setLoading(true);
                const response = await fetch("http://");

                if (!response.ok) {
                    throw new Error(`Failed to fetch: ${response.statusText}`);
                }

                const data: Cart = await response.json();
                setProducts(data);
            } catch (err: any) {
                console.error("Fetch Error:", err);
                setError(err.message);
            } finally {
                setLoading(false);
            }
        };

        fetchProducts();
    }, [cartID]);

    // 3. HandleClick function (FIXED)
    const handleClick = async (itemId: number) => {
        // Clear previous feedback for this item immediately

        const result = await addToCart(itemId);
        
        if (result) {
            setFeedback(prev => ({ ...prev, [itemId]: 'success' }));
            // Optional: Hide success message after a few seconds
            setTimeout(() => {
            }, 3000);
        } else {
            setFeedback(prev => ({ ...prev, [itemId]: 'error' }));
        }
    };

    // 4. Handle loading and error states in the render output
    if (loading) {
        return <div className="centered">Loading products...</div>;
    }

    if (error) {
        return <div className="centered" style={{ color: 'red' }}>Error: {error}</div>;
    }

    // 5. Render the list (FIXED UI)
    return (
        <div className="product-container">
            <h2>🛒 Product List</h2>
            <ul>
                {products.map((item) => {
                    const itemFeedback = feedback[item._id];
                    return (
                        // Removed data-key attribute, not needed for React components
                        <li key={item._id}>
                            <img src={"./" + item.imageLink} /><br /><br />
                            <strong>{item.name}</strong> - {item.description} - ${item.usdCentsPrice / 100} <br /><br />
                            
                            <button onClick={() => handleClick(item._id)}>Add to cart</button>
                            
                            {/* Display feedback based on state */}
                            {itemFeedback === 'success' && (
                                <span className="success" style={{ color: 'green', marginLeft: '10px' }}>
                                    Added to cart!
                                </span>
                            )}
                            {itemFeedback === 'error' && (
                                <span className="error" style={{ color: 'red', marginLeft: '10px' }}>
                                    Could not add to cart
                                </span>
                            )}
                        </li>
                    );
                })}
            </ul>
        </div>
    );
};

function Cart() {
  return (
    <>
      <Header />

      <div>
        <h1 className={"top-title"}>Cart</h1>
        <CartItems />
      </div>

      <Footer />
    </>
  );
}

export default Cart;