import React, { useState, useEffect } from 'react'; // 👈 Import hooks
import Header from "../Header";
import Footer from "../Footer";
import { getCookieValue, setCookieValue } from "../../../cookieFuncs";

// --- Types ---

interface Item {
    _id: number; // Item ID
    name: string;
    imageLink: string;
    description: string;
    usdCentsPrice: number;
}

interface ProductListProps {
}

interface Cart {
    _id: number; // Cart ID (generated by a counter)
    items: Array<ItemInCart>; // FIX 5: Use a specific interface for items in the cart
}

interface ItemInCart {
    itemId: number; // The _id of the item being referenced
    count: number; // The quantity of this item in the cart
    info: string;
}

// --- API Function (Optimized) ---

async function getCartID() {
    let cartId = Number(getCookieValue("cartId"));
    if (cartId == 0 || Number.isNaN(cartId)) {
      const response = await fetch("http://localhost:3000/get-cart");
      if (!response.ok || !response.body) {
        console.log("Could not get a cart");
        return -1;
      }
      cartId = Number(await response.text());
      if (Number.isNaN(cartId)) {
        console.log("Server returned an invalid cart ID.");
        return -1;
      }
      setCookieValue("cartId",cartId,14);
    }
    return cartId;
}

async function addToCart(itemId: number): Promise<boolean> {
    const cartID = await getCartID();

    // Use environment variable or relative path in production
    const url = 'http://localhost:3000/add-to-cart'; 
    const data = {
        itemID: itemId,
        itemCount: 1,
        cartId: cartID
    };

    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            },
            body: JSON.stringify(data)
        });

        // The key fix: Check response.ok for 2xx status codes
        // and check for the specific 201 status if required by your API.
        if (response.ok && response.status === 201) {
            return true;
        }

        // Handle other non-success status codes (e.g., 400, 404, 500)
        console.error(`Add to Cart failed with status: ${response.status}`);
        return false;

    } catch (error) {
        // Handle network errors (e.g., cannot connect to server)
        console.error('Error during POST request:', error);
        return false;
    }
}

// --- ProductList Component (Refactored to use State) ---

const ProductList: React.FC<ProductListProps> = ({  }) => {
    const [products, setProducts] = useState<Item[]>([]);
    const [cart, setCart] = useState<Cart>();
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchProducts = async () => {
            try {
                setLoading(true);
                const response = await fetch("http://localhost:3000/get-items");

                if (!response.ok) {
                    throw new Error(`Failed to fetch: ${response.statusText}`);
                }

                const data: Item[] = await response.json();
                setProducts(data);
            } catch (err: any) {
                console.error("Fetch Error:", err);
                setError(err.message);
            } finally {
                setLoading(false);
            }
        };

        const getCart = async () => {

        const cartID = await getCartID();
        console.log(cartID);
            try {
                setLoading(true);
                const response = await fetch("http://localhost:3000/get-cart-items?cartID="+cartID);

                if (!response.ok) {
                    throw new Error(`Failed to fetch: ${response.statusText}`);
                }

                const cart: Cart = await response.json();
                setCart(cart);
            } catch (err: any) {
                console.error("Fetch Error:", err);
                setError(err.message);
            } finally {
                setLoading(false);
            }
        };

        fetchProducts();
        getCart();
    }, []);

    if (loading) {
        return <div className="centered">Loading products...</div>;
    }

    if (error || !cart) {
        return <div className="centered" style={{ color: 'red' }}>Error: {error}</div>;
    }

    return (
        <div className="product-container">
            <ul>
                {cart.items.map((item, index) => {
                    return (
                        // Removed data-key attribute, not needed for React components
                        <li key={index} className='cartBox'> 
                            <img src={"./" + products[item.itemId].imageLink} className='cartImage'/><br /><br />
                            <strong>{products[item.itemId].name}</strong> <br />
                            {products[item.itemId].description}<br />
                            ${products[item.itemId].usdCentsPrice / 100}<br />
                            {item.info}<br /><br />
                            Count in cart: {item.count}
                        </li>
                    );
                })}
            </ul>
        </div>
    );
};

// --- Products Component (No changes needed) ---

function Products() {
    const apiUrl = "http://localhost:3000/get-items";

    return (
        <>
            <Header />
            <div>
                <h1 className={"top-title"}>HLM Products</h1>
                <div className={"centered"}>
                    <ProductList/>
                </div>
            </div>
            <Footer />
        </>
    );
}

export default Products;