import Header from "../Header";
import Footer from "../Footer";

interface Item {
    _id: number; // Item ID (generated by a counter)
    name: string; // Count in the cart or stock quantity in the item collection
}


const ProductList: React.FC<Item[]> = ({ products }) => {
  return (
    <div className="product-container">
      <h2>🛒 Product List</h2>
      <ul>
        {/* We map over the products array */}
        {products.map((item) => (
          // We use item._id as the unique key
          <li key={item._id}>
            <strong>ID:</strong> {item._id} | 
            <strong> Name:</strong> {item.name}
          </li>
        ))}
      </ul>
    </div>
  );
};

function Products() {

  return (
    <>
      <Header />

      <div>
        <h1 className={"top-title"}>HLM Products</h1>
        <div className={"centered"}>
            <h2>Wooden Items</h2>
        </div>
      </div>

      <Footer />
    </>
  );
}

export default Products;